package com.yeso.backend.shared.exception;

import org.springframework.http.HttpStatus;

/**
 * API 오류 코드. 코드 문자열은 프론트가 분기하는 계약이라 공개 후 바꾸지 않는다(docs/conventions/코드.md).
 * 새 코드는 상수 이름과 코드 문자열을 같게 쓰고, 자기 모듈 블록 끝에 추가한다(병렬 작업 충돌 줄이기).
 * docs/api에 적힌 MVP 코드는 미리 등록돼 있다. 구현할 때 새로 만들지 말고 여기 있는 것을 쓴다.
 */
public enum ErrorCode {
    // ---- common ----
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "COMMON_INVALID_REQUEST"),
    NOT_FOUND(HttpStatus.NOT_FOUND, "COMMON_NOT_FOUND"),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED, "COMMON_METHOD_NOT_ALLOWED"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON_INTERNAL_ERROR"),

    // ---- auth ----
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED, "AUTH_UNAUTHENTICATED"),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, "AUTH_ACCESS_DENIED"),
    DUPLICATE_EMAIL(HttpStatus.CONFLICT, "AUTH_DUPLICATE_EMAIL"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "AUTH_INVALID_CREDENTIALS"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH_INVALID_REFRESH_TOKEN"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "AUTH_USER_NOT_FOUND"),

    // ---- profile: onboarding ----
    INVALID_QUESTION_VERSION(HttpStatus.BAD_REQUEST, "ONBOARDING_INVALID_QUESTION_VERSION"),
    MISSING_QUESTION_ANSWER(HttpStatus.BAD_REQUEST, "ONBOARDING_MISSING_QUESTION_ANSWER"),
    DUPLICATE_QUESTION_ANSWER(HttpStatus.BAD_REQUEST, "ONBOARDING_DUPLICATE_QUESTION_ANSWER"),
    INVALID_CHOICE(HttpStatus.BAD_REQUEST, "ONBOARDING_INVALID_CHOICE"),
    INVALID_SCHEDULE_DENSITY(HttpStatus.BAD_REQUEST, "ONBOARDING_INVALID_SCHEDULE_DENSITY"),
    TOO_MANY_EXPERIENCE_TAGS(HttpStatus.BAD_REQUEST, "ONBOARDING_TOO_MANY_EXPERIENCE_TAGS"),
    UNKNOWN_TAG(HttpStatus.BAD_REQUEST, "ONBOARDING_UNKNOWN_TAG"),
    DUPLICATE_LIKED_REGION(HttpStatus.BAD_REQUEST, "ONBOARDING_DUPLICATE_LIKED_REGION"),
    TOO_MANY_LIKED_REGIONS(HttpStatus.BAD_REQUEST, "ONBOARDING_TOO_MANY_LIKED_REGIONS"),
    ONBOARDING_REGION_NOT_FOUND(HttpStatus.BAD_REQUEST, "ONBOARDING_REGION_NOT_FOUND"),

    // ---- profile: friend ----
    FRIEND_LINK_NOT_FOUND(HttpStatus.NOT_FOUND, "FRIEND_LINK_NOT_FOUND"),
    FRIEND_LINK_EXPIRED(HttpStatus.GONE, "FRIEND_LINK_EXPIRED"),
    FRIEND_LINK_REVOKED(HttpStatus.GONE, "FRIEND_LINK_REVOKED"),
    FRIEND_LINK_SELF(HttpStatus.BAD_REQUEST, "FRIEND_LINK_SELF"),
    FRIEND_NOT_FOUND(HttpStatus.NOT_FOUND, "FRIEND_NOT_FOUND"),
    FRIEND_REQUIRED(HttpStatus.FORBIDDEN, "FRIEND_REQUIRED"),

    // ---- trip: context ----
    INVALID_START_DATE(HttpStatus.BAD_REQUEST, "TRIP_INVALID_START_DATE"),
    INVALID_NIGHTS(HttpStatus.BAD_REQUEST, "TRIP_INVALID_NIGHTS"),
    INVALID_TRANSPORT(HttpStatus.BAD_REQUEST, "TRIP_INVALID_TRANSPORT"),
    INVALID_ORIGIN(HttpStatus.BAD_REQUEST, "TRIP_INVALID_ORIGIN"),
    TRIP_DATE_OVERLAP(HttpStatus.CONFLICT, "TRIP_DATE_OVERLAP"),
    TRIP_NOT_FOUND(HttpStatus.NOT_FOUND, "TRIP_NOT_FOUND"),
    TRIP_CONTEXT_LOCKED(HttpStatus.CONFLICT, "TRIP_CONTEXT_LOCKED"),
    TRIP_VERSION_CONFLICT(HttpStatus.CONFLICT, "TRIP_VERSION_CONFLICT"),
    TRIP_ENDED(HttpStatus.CONFLICT, "TRIP_ENDED"),
    ONBOARDING_REQUIRED(HttpStatus.CONFLICT, "ONBOARDING_REQUIRED"),
    TRIP_REGION_NOT_SELECTED(HttpStatus.CONFLICT, "TRIP_REGION_NOT_SELECTED"),
    DRAW_INVALID_MODE(HttpStatus.BAD_REQUEST, "DRAW_INVALID_MODE"),
    DRAW_NO_CONDITION_SELECTED(HttpStatus.BAD_REQUEST, "DRAW_NO_CONDITION_SELECTED"),
    DRAW_NO_ELIGIBLE_REGION(HttpStatus.UNPROCESSABLE_ENTITY, "DRAW_NO_ELIGIBLE_REGION"),
    DRAW_REGION_NOT_ELIGIBLE(HttpStatus.UNPROCESSABLE_ENTITY, "DRAW_REGION_NOT_ELIGIBLE"),
    TRIP_FULL(HttpStatus.CONFLICT, "TRIP_FULL"),

    // ---- trip: invite·share ----
    INVITE_NOT_FOUND(HttpStatus.NOT_FOUND, "INVITE_NOT_FOUND"),
    INVITE_EXPIRED(HttpStatus.GONE, "INVITE_EXPIRED"),
    INVITE_REVOKED(HttpStatus.GONE, "INVITE_REVOKED"),
    SHARE_LINK_NOT_FOUND(HttpStatus.NOT_FOUND, "SHARE_LINK_NOT_FOUND"),
    SHARE_LINK_EXPIRED(HttpStatus.GONE, "SHARE_LINK_EXPIRED"),
    SHARE_LINK_REVOKED(HttpStatus.GONE, "SHARE_LINK_REVOKED"),
    SHARE_SESSION_INVALID(HttpStatus.UNAUTHORIZED, "SHARE_SESSION_INVALID"),
    INVITE_ALREADY_HANDLED(HttpStatus.CONFLICT, "INVITE_ALREADY_HANDLED"),

    // ---- trip: course ----
    COURSE_NOT_FOUND(HttpStatus.NOT_FOUND, "COURSE_NOT_FOUND"),
    COURSE_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "COURSE_ITEM_NOT_FOUND"),
    COURSE_CREATOR_ONLY(HttpStatus.FORBIDDEN, "COURSE_CREATOR_ONLY"),
    COURSE_INVALID_OPERATION(HttpStatus.BAD_REQUEST, "COURSE_INVALID_OPERATION"),
    COURSE_INSUFFICIENT_CANDIDATES(HttpStatus.UNPROCESSABLE_ENTITY, "COURSE_INSUFFICIENT_CANDIDATES"),
    COURSE_SCHEDULE_INFEASIBLE(HttpStatus.UNPROCESSABLE_ENTITY, "COURSE_SCHEDULE_INFEASIBLE"),
    COURSE_RESTAURANT_SELECTION_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "COURSE_RESTAURANT_SELECTION_INVALID"),
    COURSE_KAKAO_LOCAL_UNAVAILABLE(HttpStatus.BAD_GATEWAY, "COURSE_KAKAO_LOCAL_UNAVAILABLE"),
    COURSE_KAKAO_LOCAL_RATE_LIMITED(HttpStatus.SERVICE_UNAVAILABLE, "COURSE_KAKAO_LOCAL_RATE_LIMITED"),

    // ---- attraction ----
    REGION_NOT_FOUND(HttpStatus.NOT_FOUND, "REGION_NOT_FOUND"),
    REGION_INVALID_DAYS(HttpStatus.BAD_REQUEST, "REGION_INVALID_DAYS"),
    REGION_CONTENT_NOT_READY(HttpStatus.UNPROCESSABLE_ENTITY, "REGION_CONTENT_NOT_READY"),
    ATTRACTION_NOT_FOUND(HttpStatus.NOT_FOUND, "ATTRACTION_NOT_FOUND"),
    ATTRACTION_INVALID_BOUNDS(HttpStatus.BAD_REQUEST, "ATTRACTION_INVALID_BOUNDS"),
    ATTRACTION_NOT_RECOMMENDABLE(HttpStatus.UNPROCESSABLE_ENTITY, "ATTRACTION_NOT_RECOMMENDABLE"),
    ATTRACTION_REGION_MISMATCH(HttpStatus.UNPROCESSABLE_ENTITY, "ATTRACTION_REGION_MISMATCH"),
    ATTRACTION_ALREADY_IN_COURSE(HttpStatus.CONFLICT, "ATTRACTION_ALREADY_IN_COURSE"),

    // ---- shared: token (초대·공유·친구 링크 공용) ----
    INVALID_EXPIRES_IN_DAYS(HttpStatus.BAD_REQUEST, "INVALID_EXPIRES_IN_DAYS"),
    TOKEN_AUDIENCE_MISMATCH(HttpStatus.BAD_REQUEST, "TOKEN_AUDIENCE_MISMATCH");

    private final HttpStatus status;
    private final String code;

    ErrorCode(HttpStatus status, String code) {
        this.status = status;
        this.code = code;
    }

    public HttpStatus status() {
        return status;
    }

    public String code() {
        return code;
    }
}
