package com.yeso.backend.shared.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "COMMON_INVALID_REQUEST"),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED, "COMMON_METHOD_NOT_ALLOWED"),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED, "AUTH_UNAUTHENTICATED"),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, "AUTH_ACCESS_DENIED"),
    DUPLICATE_EMAIL(HttpStatus.CONFLICT, "AUTH_DUPLICATE_EMAIL"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "AUTH_INVALID_CREDENTIALS"),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED, "AUTH_INVALID_REFRESH_TOKEN"),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "AUTH_USER_NOT_FOUND"),

    INVALID_QUESTION_VERSION(HttpStatus.BAD_REQUEST, "ONBOARDING_INVALID_QUESTION_VERSION"),
    MISSING_QUESTION_ANSWER(HttpStatus.BAD_REQUEST, "ONBOARDING_MISSING_QUESTION_ANSWER"),
    DUPLICATE_QUESTION_ANSWER(HttpStatus.BAD_REQUEST, "ONBOARDING_DUPLICATE_QUESTION_ANSWER"),
    INVALID_CHOICE(HttpStatus.BAD_REQUEST, "ONBOARDING_INVALID_CHOICE"),
    INVALID_SCHEDULE_DENSITY(HttpStatus.BAD_REQUEST, "ONBOARDING_INVALID_SCHEDULE_DENSITY"),
    TOO_MANY_EXPERIENCE_TAGS(HttpStatus.BAD_REQUEST, "ONBOARDING_TOO_MANY_EXPERIENCE_TAGS"),
    UNKNOWN_TAG(HttpStatus.BAD_REQUEST, "ONBOARDING_UNKNOWN_TAG"),
    DUPLICATE_LIKED_REGION(HttpStatus.BAD_REQUEST, "ONBOARDING_DUPLICATE_LIKED_REGION"),
    TOO_MANY_LIKED_REGIONS(HttpStatus.BAD_REQUEST, "ONBOARDING_TOO_MANY_LIKED_REGIONS"),
    REGION_NOT_FOUND(HttpStatus.BAD_REQUEST, "ONBOARDING_REGION_NOT_FOUND"),

    INVALID_START_DATE(HttpStatus.BAD_REQUEST, "TRIP_INVALID_START_DATE"),
    INVALID_NIGHTS(HttpStatus.BAD_REQUEST, "TRIP_INVALID_NIGHTS"),
    INVALID_TRANSPORT(HttpStatus.BAD_REQUEST, "TRIP_INVALID_TRANSPORT"),
    INVALID_ORIGIN(HttpStatus.BAD_REQUEST, "TRIP_INVALID_ORIGIN"),
    TRIP_DATE_OVERLAP(HttpStatus.CONFLICT, "TRIP_DATE_OVERLAP"),
    TRIP_NOT_FOUND(HttpStatus.NOT_FOUND, "TRIP_NOT_FOUND"),
    TRIP_CONTEXT_LOCKED(HttpStatus.CONFLICT, "TRIP_CONTEXT_LOCKED"),
    TRIP_VERSION_CONFLICT(HttpStatus.CONFLICT, "TRIP_VERSION_CONFLICT"),
    ONBOARDING_REQUIRED(HttpStatus.CONFLICT, "ONBOARDING_REQUIRED"),

    INVITE_NOT_FOUND(HttpStatus.NOT_FOUND, "INVITE_NOT_FOUND"),
    INVITE_EXPIRED(HttpStatus.GONE, "INVITE_EXPIRED"),
    INVITE_REVOKED(HttpStatus.GONE, "INVITE_REVOKED"),
    INVALID_EXPIRES_IN_DAYS(HttpStatus.BAD_REQUEST, "INVALID_EXPIRES_IN_DAYS"),
    SHARE_LINK_NOT_FOUND(HttpStatus.NOT_FOUND, "SHARE_LINK_NOT_FOUND"),
    SHARE_LINK_EXPIRED(HttpStatus.GONE, "SHARE_LINK_EXPIRED"),
    SHARE_LINK_REVOKED(HttpStatus.GONE, "SHARE_LINK_REVOKED"),
    SHARE_SESSION_INVALID(HttpStatus.UNAUTHORIZED, "SHARE_SESSION_INVALID"),
    TOKEN_AUDIENCE_MISMATCH(HttpStatus.BAD_REQUEST, "TOKEN_AUDIENCE_MISMATCH"),

    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "COMMON_INTERNAL_ERROR");

    private final HttpStatus status;
    private final String code;

    ErrorCode(HttpStatus status, String code) {
        this.status = status;
        this.code = code;
    }

    public HttpStatus status() {
        return status;
    }

    public String code() {
        return code;
    }
}
