-- 식당 자체와 원천별 근거를 분리한다. #52 TourAPI 적재는 이 스키마를 사용한다.
-- 같은 식당이 여러 공공 원천에 나오면 restaurants 한 행에 source 행을 추가할 수 있다.
CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    address TEXT,
    road_address TEXT,
    phone VARCHAR(100),
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    place_url TEXT,
    image_url TEXT,
    image_validation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    representative_menu VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_restaurant_lat CHECK (lat BETWEEN -90 AND 90),
    CONSTRAINT ck_restaurant_lng CHECK (lng BETWEEN -180 AND 180),
    CONSTRAINT ck_restaurant_image_status CHECK (image_validation_status IN ('PENDING', 'VALID', 'INVALID', 'SOURCE_EMPTY'))
);
CREATE INDEX idx_restaurants_region ON restaurants(region_id);

CREATE TABLE restaurant_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    provider VARCHAR(30) NOT NULL,
    external_id VARCHAR(100) NOT NULL,
    content_type_id INTEGER,
    source_name VARCHAR(255) NOT NULL,
    source_url TEXT,
    fetched_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    evidence_labels JSONB NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT uq_restaurant_source_external UNIQUE (provider, external_id),
    CONSTRAINT ck_restaurant_source_provider CHECK (provider IN ('TOUR_API', 'FARM_RESTAURANT', 'MODEL_RESTAURANT', 'GOOD_PRICE')),
    CONSTRAINT ck_restaurant_source_tour_type CHECK (provider <> 'TOUR_API' OR content_type_id = 39)
);
CREATE INDEX idx_restaurant_sources_restaurant ON restaurant_sources(restaurant_id);
