SET search_path TO app, public;

-- A diary is an immutable snapshot of the trip's itinerary context. trip_id intentionally has no FK:
-- leaving/deleting the last trip participant must not erase the author's travel record.
CREATE TABLE travel_diaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    title VARCHAR(60),
    body TEXT NOT NULL DEFAULT '',
    course_title VARCHAR(120) NOT NULL,
    region_sig_cd VARCHAR(5),
    visited_from DATE NOT NULL,
    visited_to DATE NOT NULL,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    location_precision VARCHAR(20) NOT NULL DEFAULT 'CITY',
    satisfaction SMALLINT,
    experience_tags TEXT NOT NULL DEFAULT '[]',
    include_in_taste_profile BOOLEAN NOT NULL DEFAULT TRUE,
    cover_photo_id BIGINT,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_travel_diaries_trip_author UNIQUE (trip_id, author_user_id),
    CONSTRAINT ck_travel_diaries_status CHECK (status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_travel_diaries_visibility CHECK (visibility IN ('PRIVATE', 'FRIENDS', 'LINK')),
    CONSTRAINT ck_travel_diaries_location_precision CHECK (location_precision IN ('EXACT', 'CITY', 'HIDDEN')),
    CONSTRAINT ck_travel_diaries_satisfaction CHECK (satisfaction IS NULL OR satisfaction BETWEEN 1 AND 5),
    CONSTRAINT ck_travel_diaries_dates CHECK (visited_to >= visited_from),
    CONSTRAINT ck_travel_diaries_experience_tags_json CHECK (jsonb_typeof(experience_tags::jsonb) = 'array')
);
CREATE INDEX idx_travel_diaries_author_visited ON travel_diaries(author_user_id, visited_from DESC, id DESC);
CREATE INDEX idx_travel_diaries_region ON travel_diaries(region_sig_cd);

-- Only object keys and safe extracted metadata are stored; the original filename and EXIF blob are not.
CREATE TABLE diary_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diary_id BIGINT NOT NULL REFERENCES travel_diaries(id) ON DELETE CASCADE,
    object_key VARCHAR(500) NOT NULL UNIQUE,
    thumbnail_key VARCHAR(500) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    byte_size BIGINT NOT NULL,
    taken_at TIMESTAMP WITHOUT TIME ZONE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    order_index INTEGER NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_diary_photos_order UNIQUE (diary_id, order_index),
    CONSTRAINT ck_diary_photos_type CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT ck_diary_photos_size CHECK (byte_size > 0 AND byte_size <= 10485760),
    CONSTRAINT ck_diary_photos_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_diary_photos_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_diary_photos_order CHECK (order_index >= 0)
);
CREATE INDEX idx_diary_photos_diary_order ON diary_photos(diary_id, order_index, id);

ALTER TABLE travel_diaries
    ADD CONSTRAINT fk_travel_diaries_cover_photo
    FOREIGN KEY (cover_photo_id) REFERENCES diary_photos(id) ON DELETE SET NULL;

-- A published diary contributes only the non-text metadata below to taste features.
CREATE TABLE diary_taste_signals (
    diary_id BIGINT PRIMARY KEY REFERENCES travel_diaries(id) ON DELETE CASCADE,
    author_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    region_sig_cd VARCHAR(5),
    satisfaction SMALLINT,
    experience_tags TEXT NOT NULL DEFAULT '[]',
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_diary_taste_signals_satisfaction CHECK (satisfaction IS NULL OR satisfaction BETWEEN 1 AND 5),
    CONSTRAINT ck_diary_taste_signals_tags_json CHECK (jsonb_typeof(experience_tags::jsonb) = 'array')
);
CREATE INDEX idx_diary_taste_signals_author ON diary_taste_signals(author_user_id);
