SET search_path TO app, public;

CREATE TABLE diary_share_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diary_id BIGINT NOT NULL REFERENCES travel_diaries(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_diary_share_links_diary_created ON diary_share_links(diary_id, created_at DESC);

CREATE TABLE diary_share_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_link_id BIGINT NOT NULL REFERENCES diary_share_links(id) ON DELETE CASCADE,
    session_token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_diary_share_sessions_link ON diary_share_sessions(share_link_id);
