CREATE SCHEMA IF NOT EXISTS app;
SET search_path TO app, public;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(190) UNIQUE,
    password_hash VARCHAR(255),
    nickname VARCHAR(30) NOT NULL,
    profile_image VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_local_credentials
        CHECK ((email IS NULL AND password_hash IS NULL) OR (email IS NOT NULL AND password_hash IS NOT NULL))
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expiry ON refresh_tokens(expires_at) WHERE revoked = FALSE;

CREATE TABLE social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_social_provider_user UNIQUE (provider, provider_user_id)
);

CREATE TABLE regions (
    sig_cd VARCHAR(5) PRIMARY KEY,
    province VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    CONSTRAINT ck_regions_sig_cd CHECK (sig_cd ~ '^[0-9]{5}$'),
    CONSTRAINT ck_regions_lat CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    CONSTRAINT ck_regions_lng CHECK (lng IS NULL OR lng BETWEEN -180 AND 180)
);

CREATE TABLE region_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd) ON DELETE CASCADE,
    title VARCHAR(120) NOT NULL,
    introduction TEXT NOT NULL,
    history_tags TEXT,
    hero_image_url TEXT,
    hero_image_source_url TEXT,
    hero_image_license_note TEXT,
    hero_image_validation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    source_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    model_version VARCHAR(100),
    prompt_version INTEGER,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    reviewed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_region_contents_version UNIQUE (region_id, prompt_version),
    CONSTRAINT ck_region_contents_status CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_region_image_status CHECK (hero_image_validation_status IN ('PENDING', 'VALID', 'INVALID', 'SOURCE_EMPTY'))
);
CREATE INDEX idx_region_contents_approved ON region_contents(region_id) WHERE status = 'APPROVED';

CREATE TABLE attractions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd),
    description TEXT,
    tags VARCHAR(1000),
    addr TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    source_system VARCHAR(30) NOT NULL DEFAULT 'TOUR_API',
    source_content_id VARCHAR(100),
    content_type_id INTEGER,
    homepage TEXT,
    use_time TEXT,
    rest_date TEXT,
    parking TEXT,
    info_center TEXT,
    tel VARCHAR(100),
    detail_fetched_at TIMESTAMP WITHOUT TIME ZONE,
    embedding_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attractions_source UNIQUE (source_system, source_content_id),
    CONSTRAINT ck_attractions_lat CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    CONSTRAINT ck_attractions_lng CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    CONSTRAINT ck_attractions_embedding_status CHECK (embedding_status IN ('PENDING', 'DONE', 'FAILED'))
);
CREATE INDEX idx_attractions_region ON attractions(region_id);
CREATE INDEX idx_attractions_recommendation_fields ON attractions(region_id, category)
    WHERE description IS NOT NULL AND lat IS NOT NULL AND lng IS NOT NULL;

CREATE TABLE attraction_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id BIGINT NOT NULL REFERENCES attractions(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    source_url TEXT,
    license_note TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    validation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    validated_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attraction_image UNIQUE (attraction_id, image_url),
    CONSTRAINT ck_attraction_image_order CHECK (display_order >= 0),
    CONSTRAINT ck_attraction_image_status CHECK (validation_status IN ('PENDING', 'VALID', 'INVALID', 'SOURCE_EMPTY'))
);
CREATE INDEX idx_attraction_images_valid ON attraction_images(attraction_id) WHERE validation_status = 'VALID';

CREATE TABLE attraction_embeddings (
    attraction_id BIGINT PRIMARY KEY REFERENCES attractions(id) ON DELETE CASCADE,
    embedding BYTEA NOT NULL,
    dimension INTEGER NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    template_version INTEGER NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_attraction_embedding_dimension CHECK (dimension > 0)
);

CREATE TABLE onboarding_submissions (
    id UUID PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    guest_participant_id BIGINT,
    question_version INTEGER NOT NULL,
    travel_mbti VARCHAR(20),
    profile_text TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_onboarding_owner CHECK ((user_id IS NOT NULL)::int + (guest_participant_id IS NOT NULL)::int = 1)
);

CREATE TABLE onboarding_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id UUID NOT NULL REFERENCES onboarding_submissions(id) ON DELETE CASCADE,
    question_key VARCHAR(100) NOT NULL,
    answer_value JSONB NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_onboarding_answer UNIQUE (submission_id, question_key)
);

CREATE TABLE liked_trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id UUID NOT NULL REFERENCES onboarding_submissions(id) ON DELETE CASCADE,
    region_id VARCHAR(5) REFERENCES regions(sig_cd),
    display_name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Transitional entity table. WORK-02 migrates callers to submissions/answers and removes this table in a later version.
CREATE TABLE onboarding_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    submission_id VARCHAR(36) NOT NULL,
    question_key VARCHAR(255) NOT NULL,
    answer_value TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_onboarding_responses_submission ON onboarding_responses(user_id, submission_id);

CREATE TABLE user_taste_vectors (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    embedding BYTEA NOT NULL,
    dimension INTEGER NOT NULL,
    profile_text TEXT NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    template_version INTEGER NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_taste_dimension CHECK (dimension > 0)
);

CREATE TABLE guest_taste_vectors (
    guest_participant_id BIGINT PRIMARY KEY,
    embedding BYTEA NOT NULL,
    profile_text TEXT NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    template_version INTEGER NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE official_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd),
    source_system VARCHAR(30) NOT NULL DEFAULT 'TOUR_API',
    source_content_id VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    theme VARCHAR(120),
    total_distance_text VARCHAR(100),
    fetched_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_official_courses_source UNIQUE (source_system, source_content_id)
);
CREATE INDEX idx_official_courses_region ON official_courses(region_id);

CREATE TABLE official_course_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    official_course_id BIGINT NOT NULL REFERENCES official_courses(id) ON DELETE CASCADE,
    stop_order INTEGER NOT NULL,
    attraction_id BIGINT REFERENCES attractions(id) ON DELETE SET NULL,
    source_content_id VARCHAR(100),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    image_url TEXT,
    CONSTRAINT uq_official_course_stop_order UNIQUE (official_course_id, stop_order),
    CONSTRAINT ck_official_course_stop_order CHECK (stop_order >= 0)
);

CREATE TABLE trip_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd),
    title VARCHAR(120),
    transport VARCHAR(20) NOT NULL,
    origin_lat DOUBLE PRECISION,
    origin_lng DOUBLE PRECISION,
    situation TEXT,
    status VARCHAR(20) NOT NULL,
    start_date DATE,
    end_date DATE,
    arrival_time TIME WITHOUT TIME ZONE,
    departure_time TIME WITHOUT TIME ZONE,
    overlap_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    idempotency_key VARCHAR(100),
    request_hash VARCHAR(64),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_trip_idempotency UNIQUE (owner_user_id, idempotency_key),
    CONSTRAINT ck_trip_dates CHECK (start_date IS NULL OR end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_trip_status CHECK (status IN ('DRAFT', 'CONFIRMED')),
    CONSTRAINT ck_trip_transport CHECK (transport IN ('WALK', 'CAR', 'PUBLIC_TRANSIT'))
);
CREATE INDEX idx_trip_plans_owner_dates ON trip_plans(owner_user_id, start_date, end_date);

CREATE TABLE trip_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_trip_member UNIQUE (trip_plan_id, user_id),
    CONSTRAINT ck_trip_member_role CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE TABLE trip_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    participant_type VARCHAR(20) NOT NULL,
    display_name VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'INVITED',
    taste_snapshot JSONB,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_participant_type CHECK (participant_type IN ('OWNER', 'USER', 'GUEST')),
    CONSTRAINT ck_participant_status CHECK (status IN ('INVITED', 'ONBOARDING', 'READY', 'REVOKED'))
);
ALTER TABLE onboarding_submissions
    ADD CONSTRAINT fk_onboarding_guest_participant
    FOREIGN KEY (guest_participant_id) REFERENCES trip_participants(id) ON DELETE CASCADE;
ALTER TABLE guest_taste_vectors
    ADD CONSTRAINT fk_guest_taste_participant
    FOREIGN KEY (guest_participant_id) REFERENCES trip_participants(id) ON DELETE CASCADE;

CREATE TABLE trip_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    attraction_id BIGINT NOT NULL REFERENCES attractions(id),
    visit_date DATE,
    start_time TIME WITHOUT TIME ZONE,
    end_time TIME WITHOUT TIME ZONE,
    stay_minutes INTEGER,
    travel_minutes_from_previous INTEGER,
    distance_meters_from_previous INTEGER,
    estimated BOOLEAN NOT NULL DEFAULT TRUE,
    order_index INTEGER NOT NULL,
    source VARCHAR(20) NOT NULL,
    CONSTRAINT uq_trip_stop_order UNIQUE (trip_plan_id, visit_date, order_index),
    CONSTRAINT ck_trip_stop_source CHECK (source IN ('RECOMMEND', 'MANUAL')),
    CONSTRAINT ck_trip_stop_order CHECK (order_index >= 0),
    CONSTRAINT ck_trip_stop_duration CHECK (stay_minutes IS NULL OR stay_minutes > 0)
);

CREATE TABLE meal_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    visit_date DATE NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    provider VARCHAR(30),
    provider_place_id VARCHAR(100),
    place_name VARCHAR(255),
    address_name TEXT,
    road_address_name TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    place_url TEXT,
    category_name TEXT,
    representative_menu VARCHAR(255),
    order_index INTEGER NOT NULL,
    CONSTRAINT uq_meal_stop_order UNIQUE (trip_plan_id, visit_date, order_index),
    CONSTRAINT ck_meal_type CHECK (meal_type IN ('LUNCH', 'DINNER')),
    CONSTRAINT ck_meal_time CHECK (end_time > start_time)
);

CREATE TABLE trip_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    invited_by_user_id BIGINT NOT NULL REFERENCES users(id),
    participant_id BIGINT REFERENCES trip_participants(id) ON DELETE SET NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE course_share_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    permission VARCHAR(10) NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_share_permission CHECK (permission IN ('VIEW', 'EDIT'))
);

CREATE TABLE friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_low_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_high_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    requested_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friendship_pair UNIQUE (user_low_id, user_high_id),
    CONSTRAINT ck_friendship_order CHECK (user_low_id < user_high_id),
    CONSTRAINT ck_friendship_status CHECK (status IN ('PENDING', 'ACCEPTED'))
);

CREATE TABLE user_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    attraction_id BIGINT NOT NULL REFERENCES attractions(id) ON DELETE CASCADE,
    action VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_interaction_action CHECK (action IN ('VIEW', 'LIKE', 'SAVE'))
);
CREATE INDEX idx_user_interactions_user_created ON user_interactions(user_id, created_at DESC);

CREATE TABLE ingestion_runs (
    id UUID PRIMARY KEY,
    job_type VARCHAR(50) NOT NULL,
    source_system VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    cursor_value VARCHAR(255),
    requested_limit INTEGER,
    call_count INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    source_checksum VARCHAR(64),
    application_version VARCHAR(100),
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT ck_ingestion_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'QUOTA_EXHAUSTED'))
);

CREATE TABLE data_quality_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id UUID REFERENCES ingestion_runs(id) ON DELETE SET NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_key VARCHAR(255) NOT NULL,
    issue_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_quality_issue_open UNIQUE (entity_type, entity_key, issue_type, status),
    CONSTRAINT ck_quality_severity CHECK (severity IN ('INFO', 'WARNING', 'ERROR')),
    CONSTRAINT ck_quality_status CHECK (status IN ('OPEN', 'RESOLVED', 'IGNORED'))
);
CREATE INDEX idx_quality_issues_open ON data_quality_issues(issue_type, entity_type) WHERE status = 'OPEN';
