SET search_path TO app, public;

-- 지역·관광지 한 줄 소개와 태그(#89, docs/api/attraction.md "한 줄 소개와 태그"). LLM 초안 → 사람 승인.
-- APPROVED만 API에 나간다. 원천 설명(attractions.description)·지역 소개(region_contents)를 덮어쓰지 않도록 전용 테이블에 둔다.
-- 표시용이라 임베딩 문장에 넣지 않는다.
-- source_hash: 근거(이름·분류·설명, 지역은 대표 관광지)와 프롬프트 버전의 SHA-256. 바뀌면 다시 생성하고 DRAFT로 돌린다.
-- tags: 2026-10-10 확정 태그 사전의 값만, 최대 4개. 사전을 바꾸면 이 제약과 SummaryTags, ai tags.py를 함께 바꾼다.

CREATE TABLE attraction_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attraction_id BIGINT NOT NULL REFERENCES attractions(id) ON DELETE CASCADE,
    one_line VARCHAR(100) NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    basis VARCHAR(20) NOT NULL,
    source_hash CHAR(64) NOT NULL,
    generator_model VARCHAR(100),
    prompt_version VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    reviewed_by VARCHAR(100),
    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    review_note TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attraction_summaries_attraction UNIQUE (attraction_id),
    CONSTRAINT ck_attraction_summaries_basis CHECK (basis IN ('SOURCE_SUMMARY', 'NAME_CATEGORY')),
    CONSTRAINT ck_attraction_summaries_status CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_attraction_summaries_one_line CHECK (btrim(one_line) <> ''),
    CONSTRAINT ck_attraction_summaries_tags CHECK (
        jsonb_typeof(tags) = 'array'
        AND jsonb_array_length(tags) <= 4
        AND tags <@ '["바다","산","숲","호수·강","섬","꽃","역사","전통","박물관","사찰","시장","카페","야경","골목","액티비티","산책","체험","감성여행","힐링","가족여행","데이트"]'::jsonb
    ),
    CONSTRAINT ck_attraction_summaries_review CHECK (status = 'DRAFT' OR reviewed_at IS NOT NULL)
);
CREATE INDEX idx_attraction_summaries_status ON attraction_summaries(status);

CREATE TABLE region_summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd) ON DELETE CASCADE,
    tagline VARCHAR(60) NOT NULL,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    basis_attraction_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_hash CHAR(64) NOT NULL,
    generator_model VARCHAR(100),
    prompt_version VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    reviewed_by VARCHAR(100),
    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    review_note TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_region_summaries_region UNIQUE (region_id),
    CONSTRAINT ck_region_summaries_status CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_region_summaries_tagline CHECK (btrim(tagline) <> ''),
    CONSTRAINT ck_region_summaries_tags CHECK (
        jsonb_typeof(tags) = 'array'
        AND jsonb_array_length(tags) <= 4
        AND tags <@ '["바다","산","숲","호수·강","섬","꽃","역사","전통","박물관","사찰","시장","카페","야경","골목","액티비티","산책","체험","감성여행","힐링","가족여행","데이트"]'::jsonb
    ),
    CONSTRAINT ck_region_summaries_basis CHECK (jsonb_typeof(basis_attraction_ids) = 'array'),
    CONSTRAINT ck_region_summaries_review CHECK (status = 'DRAFT' OR reviewed_at IS NOT NULL)
);
CREATE INDEX idx_region_summaries_status ON region_summaries(status);

COMMENT ON COLUMN attraction_summaries.basis IS 'SOURCE_SUMMARY: 원천 설명 요약, NAME_CATEGORY: 설명이 없어 이름·분류만으로 쓴 초안(승인 필수, 화면에 구분 표시)';
COMMENT ON COLUMN region_summaries.basis_attraction_ids IS '태그라인 근거로 쓴 대표 관광지 ID 목록(검수자가 대조한다)';
