SET search_path TO app, public;

-- question_version 문자열화(예: 'demo-mbti-v1'), travel_mbti는 mbti_code로 이름을 맞춘다.
ALTER TABLE onboarding_submissions
    ALTER COLUMN question_version TYPE VARCHAR(50) USING question_version::text;
ALTER TABLE onboarding_submissions RENAME COLUMN travel_mbti TO mbti_code;

ALTER TABLE onboarding_submissions
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    ADD COLUMN taste_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    ADD COLUMN completed_at TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN schedule_density VARCHAR(20),
    ADD COLUMN experience_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN exclude_tags JSONB NOT NULL DEFAULT '[]'::jsonb;

UPDATE onboarding_submissions SET schedule_density = 'RELAXED' WHERE schedule_density IS NULL;
ALTER TABLE onboarding_submissions ALTER COLUMN schedule_density SET NOT NULL;

ALTER TABLE onboarding_submissions
    ADD CONSTRAINT ck_onboarding_submission_status CHECK (status IN ('SUBMITTED')),
    ADD CONSTRAINT ck_onboarding_taste_status CHECK (taste_status IN ('PENDING', 'READY', 'FAILED')),
    ADD CONSTRAINT ck_onboarding_schedule_density CHECK (schedule_density IN ('RELAXED', 'PACKED'));

-- 좋았던 여행지: sigCd당 한 번, 태그/메모를 갖는다. display_name(자유 라벨)은 새 계약에 없다.
ALTER TABLE liked_trips
    DROP COLUMN display_name,
    ADD COLUMN note VARCHAR(500),
    ADD COLUMN tags JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE liked_trips ALTER COLUMN region_id SET NOT NULL;
ALTER TABLE liked_trips
    ADD CONSTRAINT uq_liked_trip_submission_region UNIQUE (submission_id, region_id);

-- user/guest 최신 제출 pointer. 재검사는 새 submission을 만들고 이 pointer만 바꾼다.
ALTER TABLE users
    ADD COLUMN latest_onboarding_submission_id UUID REFERENCES onboarding_submissions(id) ON DELETE SET NULL;
ALTER TABLE trip_participants
    ADD COLUMN latest_onboarding_submission_id UUID REFERENCES onboarding_submissions(id) ON DELETE SET NULL;

-- 임베딩 job 상태·재시도 bookkeeping. user_taste_vectors/guest_taste_vectors는 READY일 때만 row가 생긴다.
CREATE TABLE embedding_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id UUID NOT NULL REFERENCES onboarding_submissions(id) ON DELETE CASCADE,
    owner_type VARCHAR(10) NOT NULL,
    owner_id BIGINT NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    template_version INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITHOUT TIME ZONE,
    last_error_code VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_embedding_jobs_submission UNIQUE (submission_id),
    CONSTRAINT ck_embedding_job_owner_type CHECK (owner_type IN ('USER', 'GUEST')),
    CONSTRAINT ck_embedding_job_status CHECK (status IN ('PENDING', 'READY', 'FAILED'))
);
CREATE INDEX idx_embedding_jobs_due ON embedding_jobs(next_attempt_at) WHERE status = 'PENDING';

-- 기존 코드에서 더 이상 쓰지 않는 전환용 테이블 제거(WORK-00 baseline 주석 참고).
DROP TABLE onboarding_responses;
