SET search_path TO app, public;

CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id VARCHAR(5) NOT NULL REFERENCES regions(sig_cd),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    addr TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    description TEXT,
    image_url TEXT,
    image_validation_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    use_time TEXT,
    detail_fetched BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_restaurants_lat CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    CONSTRAINT ck_restaurants_lng CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    CONSTRAINT ck_restaurants_image_status CHECK (image_validation_status IN ('PENDING', 'VALID', 'INVALID', 'SOURCE_EMPTY'))
);
CREATE INDEX idx_restaurants_region ON restaurants(region_id);

CREATE TABLE restaurant_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
    source_system VARCHAR(30) NOT NULL,
    source_content_id VARCHAR(100) NOT NULL,
    source_url TEXT,
    fetched_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_restaurant_source UNIQUE (source_system, source_content_id)
);
CREATE INDEX idx_restaurant_sources_restaurant ON restaurant_sources(restaurant_id);
