SET search_path TO app, public;

-- 초대 링크: revoked를 refresh_tokens/onboarding_submissions와 같은 revoked_at 패턴으로 통일한다.
-- participant_id(단일 FK)는 "링크 하나에 손님 여러 명"과 맞지 않아 제거하고,
-- 대신 trip_participants 쪽에서 어떤 초대로 들어왔는지 역참조한다.
ALTER TABLE trip_invitations
    ADD COLUMN revoked_at TIMESTAMP WITHOUT TIME ZONE,
    -- 이 링크로 들어온 손님이 확정 일정에 대해 갖는 기본 권한이다. course_share_links와 같은 값 집합을 쓴다.
    ADD COLUMN permission VARCHAR(10) NOT NULL DEFAULT 'VIEW';
UPDATE trip_invitations SET revoked_at = CURRENT_TIMESTAMP WHERE revoked = TRUE;
ALTER TABLE trip_invitations DROP COLUMN revoked;
ALTER TABLE trip_invitations DROP COLUMN participant_id;
ALTER TABLE trip_invitations ALTER COLUMN permission DROP DEFAULT;
ALTER TABLE trip_invitations
    ADD CONSTRAINT ck_invite_permission CHECK (permission IN ('VIEW', 'EDIT'));
CREATE INDEX idx_trip_invitations_active ON trip_invitations(trip_plan_id) WHERE revoked_at IS NULL;

-- latest_onboarding_submission_id는 V3가 이미 추가했다. 여기서는 어느 초대로 들어왔는지만 더한다.
ALTER TABLE trip_participants
    ADD COLUMN trip_invitation_id BIGINT REFERENCES trip_invitations(id) ON DELETE SET NULL;

-- guest 세션: 가입 없이 이후 요청(온보딩 제출 등)을 인증하는 opaque bearer. 참여자당 하나다.
CREATE TABLE guest_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT NOT NULL UNIQUE REFERENCES trip_participants(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- WORK-00 baseline이 dimension 컬럼을 빠뜨렸다(user_taste_vectors에는 있음) — user 쪽과 같은 모양으로 맞춘다.
-- guest 참여자 자체가 이번 작업에서 처음 생기므로 기존 행은 없고, DEFAULT는 컬럼 추가용으로만 쓴다.
ALTER TABLE guest_taste_vectors ADD COLUMN dimension INTEGER NOT NULL DEFAULT 0;
ALTER TABLE guest_taste_vectors ALTER COLUMN dimension DROP DEFAULT;
ALTER TABLE guest_taste_vectors ADD CONSTRAINT ck_guest_taste_dimension CHECK (dimension > 0);

-- 공유 링크도 같은 revoked_at 패턴으로 통일한다.
ALTER TABLE course_share_links ADD COLUMN revoked_at TIMESTAMP WITHOUT TIME ZONE;
UPDATE course_share_links SET revoked_at = CURRENT_TIMESTAMP WHERE revoked = TRUE;
ALTER TABLE course_share_links DROP COLUMN revoked;
CREATE INDEX idx_course_share_links_active ON course_share_links(trip_plan_id) WHERE revoked_at IS NULL;

-- 공유 링크 open 시 URL의 원문 token을 짧은 HttpOnly 세션으로 교환한다(이후 URL에는 token이 없다).
CREATE TABLE share_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_link_id BIGINT NOT NULL REFERENCES course_share_links(id) ON DELETE CASCADE,
    session_token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
