-- 친구 초대 링크(docs/api/profile.md 2-4~2-8). 원문 token은 저장하지 않고 SHA-256 해시만 둔다.
-- 폐기 전까지 여러 명이 수락할 수 있고, 새로 친구가 된 수를 accepted_count로 센다.
CREATE TABLE friend_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    accepted_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_friend_link_accepted_count CHECK (accepted_count >= 0)
);

CREATE INDEX idx_friend_links_created_by ON friend_links (created_by_user_id, created_at DESC);

-- 링크 수락은 바로 ACCEPTED로 저장한다. 친구 목록 조회용 인덱스.
CREATE INDEX idx_friendships_user_low ON friendships (user_low_id);
CREATE INDEX idx_friendships_user_high ON friendships (user_high_id);
