-- 친구 직접 초대(docs/api/trip.md 4-6~4-8, 4-14, 4-15). token 기반 trip_invitations와 별도 테이블이다.
-- 대기 중인 초대는 (여행, 초대받는 사람)마다 하나다. 처리된 초대(ACCEPTED·DECLINED·CANCELLED)는 이력으로 남고,
-- 거절·취소 뒤에는 새 초대를 만들 수 있다.
CREATE TABLE trip_friend_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    inviter_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    invitee_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    handled_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_trip_friend_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED')),
    CONSTRAINT ck_trip_friend_invitation_handled CHECK ((status = 'PENDING') = (handled_at IS NULL))
);

CREATE UNIQUE INDEX uq_trip_friend_invitation_pending
    ON trip_friend_invitations (trip_plan_id, invitee_user_id) WHERE status = 'PENDING';
CREATE INDEX idx_trip_friend_invitations_trip ON trip_friend_invitations (trip_plan_id, created_at DESC);
CREATE INDEX idx_trip_friend_invitations_invitee ON trip_friend_invitations (invitee_user_id, status);
