-- 코스를 시각 없는 날짜별 순서 목록으로 저장한다(docs/api/trip.md 5장, 2026-09-25 결정).
-- 관광지와 식사를 한 목록(course_items)에 두고, 고른 식당은 식사 행에 1:1로 따로 둔다(course_meal_restaurants).
-- trip_stops·meal_stops는 한 번도 쓰지 않은 빈 테이블이라 지운다.

DROP TABLE trip_stops;
DROP TABLE meal_stops;

CREATE TABLE course_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_plan_id BIGINT NOT NULL REFERENCES trip_plans(id) ON DELETE CASCADE,
    day_index INTEGER NOT NULL,
    order_index INTEGER NOT NULL,
    kind VARCHAR(20) NOT NULL,
    attraction_id BIGINT REFERENCES attractions(id),
    meal_type VARCHAR(20),
    stay_minutes INTEGER NOT NULL,
    travel_minutes_from_previous INTEGER,
    source VARCHAR(20),
    reason TEXT,
    CONSTRAINT ck_course_item_kind CHECK (kind IN ('ATTRACTION', 'MEAL')),
    CONSTRAINT ck_course_item_meal_type CHECK (meal_type IS NULL OR meal_type IN ('LUNCH', 'DINNER')),
    CONSTRAINT ck_course_item_source CHECK (source IS NULL OR source IN ('RECOMMEND', 'MANUAL')),
    -- 관광지는 attraction_id·source가 필수이고 meal_type이 없다. 식사는 그 반대다.
    CONSTRAINT ck_course_item_shape CHECK (
        (kind = 'ATTRACTION' AND attraction_id IS NOT NULL AND source IS NOT NULL AND meal_type IS NULL)
        OR (kind = 'MEAL' AND meal_type IS NOT NULL AND attraction_id IS NULL AND source IS NULL)
    ),
    CONSTRAINT ck_course_item_day CHECK (day_index >= 0),
    CONSTRAINT ck_course_item_order CHECK (order_index >= 0),
    CONSTRAINT ck_course_item_stay CHECK (stay_minutes > 0),
    CONSTRAINT ck_course_item_travel CHECK (travel_minutes_from_previous IS NULL OR travel_minutes_from_previous >= 0),
    -- 순서를 바꾸는 편집은 여러 행의 order_index를 한꺼번에 고치므로 커밋 시점에 검사한다.
    CONSTRAINT uq_course_item_order UNIQUE (trip_plan_id, day_index, order_index) DEFERRABLE INITIALLY DEFERRED,
    -- course_meal_restaurants가 "식사인 항목"만 참조하도록 (id, kind)를 외래키 대상으로 연다.
    CONSTRAINT uq_course_item_id_kind UNIQUE (id, kind)
);

CREATE INDEX idx_course_items_attraction ON course_items (attraction_id);

-- 날마다 점심·저녁은 하나씩이다. 식사는 같은 날 안에서만 순서를 옮긴다.
CREATE UNIQUE INDEX uq_course_item_meal_per_day ON course_items (trip_plan_id, day_index, meal_type) WHERE kind = 'MEAL';

-- 식사 자리에 고른 식당의 스냅샷(docs/api/trip.md 5장 RestaurantSnapshot). 식사 한 자리에 식당 하나.
CREATE TABLE course_meal_restaurants (
    course_item_id BIGINT PRIMARY KEY,
    -- 항상 'MEAL'. (course_item_id, item_kind)로 course_items(id, kind)를 참조해 관광지 항목에는 붙지 않게 한다.
    item_kind VARCHAR(20) NOT NULL DEFAULT 'MEAL',
    provider VARCHAR(30) NOT NULL,
    external_id VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    address TEXT,
    road_address TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    phone VARCHAR(100),
    place_url TEXT,
    image_url TEXT,
    representative_menu VARCHAR(255),
    evidence_labels JSONB NOT NULL DEFAULT '[]'::jsonb,
    sources JSONB NOT NULL DEFAULT '[]'::jsonb,
    selected_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    selected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_course_meal_restaurant_provider
        CHECK (provider IN ('TOUR_API', 'FARM_RESTAURANT', 'MODEL_RESTAURANT', 'GOOD_PRICE', 'KAKAO')),
    CONSTRAINT ck_course_meal_restaurant_lat CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    CONSTRAINT ck_course_meal_restaurant_lng CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    CONSTRAINT ck_course_meal_restaurant_item_kind CHECK (item_kind = 'MEAL'),
    CONSTRAINT fk_course_meal_restaurant_item FOREIGN KEY (course_item_id, item_kind)
        REFERENCES course_items (id, kind) ON DELETE CASCADE
);

-- 코스 정보. 코스를 비우면(3-7 replaceCourse) course_first_generated_at만 남기고 나머지를 비운다.
ALTER TABLE trip_plans
    ADD COLUMN title_source VARCHAR(20),
    ADD COLUMN recommendation_mode VARCHAR(20),
    ADD COLUMN taste_basis_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN course_updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN course_updated_at TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN course_first_generated_at TIMESTAMP WITHOUT TIME ZONE,
    ADD CONSTRAINT ck_trip_title_source CHECK (title_source IS NULL OR title_source IN ('RULE', 'LLM')),
    ADD CONSTRAINT ck_trip_recommendation_mode
        CHECK (recommendation_mode IS NULL OR recommendation_mode IN ('PERSONALIZED', 'TOUR_OFFICIAL', 'RULE_BASED'));
